### ISSUE TITLE
[Quest] [Legion Server] Demon Hunter - starting questline

### ISSUE THREAD

**Issue by Dzikirys** [holydeew/WoWHellgarve#10]
Quests are not showing for me. I see quest and npcs only when i have Game Master mode on :) Thank you
~Greeting Dzikirys
![WoWScrnShot_030821_114147](https://user-images.githubusercontent.com/80256210/110312193-11fe4380-8005-11eb-960c-566e632a5fa6.jpg)
![WoWScrnShot_030821_114152](https://user-images.githubusercontent.com/80256210/110312198-1296da00-8005-11eb-99ea-7a8b866215f6.jpg)
![WoWScrnShot_030821_114155](https://user-images.githubusercontent.com/80256210/110312202-13c80700-8005-11eb-8519-b6f00df9f211.jpg)
![WoWScrnShot_030821_114205](https://user-images.githubusercontent.com/80256210/110312208-14609d80-8005-11eb-9beb-840e39615120.jpg)
![WoWScrnShot_030821_114213](https://user-images.githubusercontent.com/80256210/110312212-14f93400-8005-11eb-9f17-c20ce8344123.jpg)
![WoWScrnShot_030821_114226](https://user-images.githubusercontent.com/80256210/110312214-1591ca80-8005-11eb-84cc-6d04483cbf52.jpg)
![WoWScrnShot_030821_114426](https://user-images.githubusercontent.com/80256210/110312215-162a6100-8005-11eb-9f7d-dc4f560c0dc9.jpg)
![WoWScrnShot_030821_114521](https://user-images.githubusercontent.com/80256210/110312219-16c2f780-8005-11eb-81b2-4915328431a3.jpg)

**Comment by OMGhixD-OG** [comment]
Unable to reproduce.
