### ISSUE TITLE
[BUG]Ulduar/Raid

### ISSUE THREAD

**Issue by jjlupaca** [holydeew/WoWHellgarve#103]
Quest/Spell/Item/Creature(ID) The ID is: https://www.wowhead.com/search?q=ulduar

The Current Behaviour is as following: Expedition commander should start hunting the boss

Expected Behaviour should be as following: Expedition commander does not work when giving the order

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/80786157/111508885-2d123700-871a-11eb-8994-0cb3cd03da55.png)

Additional Information:

**Comment by Lujanamma** [comment]
what modality? i tried to reproduce it but whole encounter works correctly
