### ISSUE TITLE
[BUG]Gilneas city Starting Quest

### ISSUE THREAD

**Issue by onghama** [holydeew/WoWHellgarve#104]
Quest/Spell/Item/Creature(ID) The ID is: SALVAGE THE SUPPLIES - npc : Gwen Armstead

The Current Behaviour is as following: QUEST ITEMS ARE NOT SHOWING IN THE DESIGNATED AREA

Expected Behaviour should be as following: SHOULD BE CRATERS AROUND THE AREA TO GET

Screenshot/Video (IMGUR/YOUTUBE): https://imgur.com/4XXtSNn

Additional Information: world location : Gilneas city...questing cannot be completed without the completion of the bug....also the npcs are jumping around with the rushing sound....targeting wolf npcs sometimes doesnt work

**Comment by Lujanamma** [comment]
fixed
