### ISSUE TITLE
[BUG]Vault of the Wardens - A New Direction Quest

### ISSUE THREAD

**Issue by onghama** [holydeew/WoWHellgarve#105]
Quest/Spell/Item/Creature(ID) The ID is: A new direction

The Current Behaviour is as following: Quest pannel isn't showing both choices

Expected Behaviour should be as following: shows two botton to click on to chose either *Kayn Sunfury* or *Altruis the Sufferer*

Screenshot/Video (IMGUR/YOUTUBE): https://imgur.com/7VZ7H6H

Additional Information:

**Comment by Lujanamma** [comment]
fixed
