### ISSUE TITLE
[NPC] Inkeeper Grosk - set HS bug

### ISSUE THREAD

**Issue by ffighter29** [holydeew/WoWHellgarve#107]
**Quest/Spell/Item/Creature(ID) The ID is:** 
npc link: https://www.wowhead.com/npc=6928/innkeeper-grosk
**The Current Behaviour is as following:** 
gossip options are wrong or do nothing, currently store opens on "what can i do at an inn?" gossip while others have no effects
**Expected Behaviour should be as following:** 
check image bellow
**Screenshot/Video (IMGUR/YOUTUBE):** 
![image](https://user-images.githubusercontent.com/7666694/111678871-07bc2080-8821-11eb-80af-601bd23a9a5a.png)

**Additional Information:**

**Comment by Lujanamma** [comment]
fixed
