### ISSUE TITLE
[BUG]Scarlet Monastery

### ISSUE THREAD

**Issue by onghama** [holydeew/WoWHellgarve#118]
Quest/Spell/Item/Creature(ID) The ID is: Killing High inquisitor Whitemane

The Current Behaviour is as following: she doesn't move or attack. she talk without engaging to combat, even when drained she doesn't die

Expected Behaviour should be as following: to be killed and using Blades of the anoited on her corpse

Screenshot/Video (IMGUR/YOUTUBE): https://imgur.com/ftwrhJv

Additional Information:

**Comment by Lujanamma** [comment]
fixed
