### ISSUE TITLE
Druid Completely broken

### ISSUE THREAD

**Issue by GM-shadow** [holydeew/WoWHellgarve#12]
Fur Spec: Druid 
Ferocious Bite ID: 22568 
Shred              ID: 5221
Rake               ID: 1822
this  class has been broken for a long time now  needs urgent attention
 added broken skills to player once relogged  they where removed again

**Comment by Lujanamma** [comment]
Is it working now? i need updated bug list

**Comment by Lujanamma** [comment]
fixed. you may find this visual bug at a times, but with relogging it will be fixed. tested and worked
