### ISSUE TITLE
2+ Seat Mounts Broken, List

### ISSUE THREAD

**Issue by GM-shadow** [holydeew/WoWHellgarve#13]
players  cannot mount or Npcs Missing  
https://www.wowhead.com/item=54860/x-53-touring-rocket
https://www.wowhead.com/item=65891/vial-of-the-sands
https://www.wowhead.com/item=44413/mekgineers-chopper                                (Alliance)
https://www.wowhead.com/item=41508/mechano-hog                                           (Horde)
https://www.wowhead.com/item=44235/reins-of-the-travelers-tundra-mammoth  (Alliance)
https://www.wowhead.com/item=44234/reins-of-the-travelers-tundra-mammoth  (Horde)
https://www.wowhead.com/item=84101/reins-of-the-grand-expedition-yak

**Comment by Lujanamma** [comment]
fixed
