### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by elemlightx** [holydeew/WoWHellgarve#130]
THE Problem is that when i try to walk and turning the camera around i can't it there is a problem in the mouse like when i walk straight ahead( forward) i can't see the cursor even when i use a keybind walking forward and not the mouse it is really uncofortable

**Comment by OMGhixD-OG** [comment]
This is not a serverside issue, and this is nothing we can fix. This is unfortunately all on the client(side). 

Closing.
