### ISSUE TITLE
I lost my items from AH [BUG]

### ISSUE THREAD

**Issue by majdmegtudod** [holydeew/WoWHellgarve#131]
Quest/Spell/Item/Creature(ID) The ID is: item=1728    ,,,, item=1263

The Current Behaviour is as following:  I put this two items in the AH last night and today when i woke up I went to check if somebody was buying them or not then I see they where dissapeard they are gone, I checked all my charakter they are gone now ,no mail nothing , my auctions site is empty in AH  ( Worlddruid is my character name)

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by holydeew** [comment]
Hello, open a ticket on discord we will refund your lost :)

**Comment by holydeew** [comment]
Hello, open a ticket on discord, your lost will be refund.
we are working hard to fix that issue soon. stay tune ^^

**Comment by majdmegtudod** [comment]
Hello, I have no idea how to open a ticket on discord ,where should I write?

**Comment by OMGhixD-OG** [comment]
> Hello, I have no idea how to open a ticket on discord ,where should I write?

Create your **own** report here https://github.com/holydeew/WoWHellgarve/issues and include as much information as you can.

**Comment by OMGhixD-OG** [comment]
Issue resolved per Discord Ticket

Closing.
