### ISSUE TITLE
[In game Bug] [Legion Server] Fly path in Shal'aran - Suramar

### ISSUE THREAD

**Issue by Dzikirys** [holydeew/WoWHellgarve#16]
This pretty purple hippohryphon kicked me from game. I mean he's just crashed game xD
~GM Dzikirys
![image](https://user-images.githubusercontent.com/80256210/110342410-a9768d00-802b-11eb-9b5e-7ec87375959f.png)

**Comment by Lujanamma** [comment]
not using legion realm anymore
