### ISSUE TITLE
[BUG] Quest In Duskwood: The Embalmers revenge

### ISSUE THREAD

**Issue by Loki661218** [holydeew/WoWHellgarve#162]
Quest/Spell/Item/Creature(ID) The ID is: The Embalmer's revenge

The Current Behaviour is as following: no monster (stitches) spawning in highlighted zone

Expected Behaviour should be as following: the monster called stitches should appear in the village so it can be slained and the quest can be completed in duskwood.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by OMGhixD-OG** [comment]
Stitches should spawn accordingly after accepting quest "The Embalmer's Revenge" now.

Thank you for the report!
