### ISSUE TITLE
[BUG]Quest In Stranglethorn: Deep Roots

### ISSUE THREAD

**Issue by Loki661218** [holydeew/WoWHellgarve#165]
Quest/Spell/Item/Creature(ID) The ID is: Quest: Deep Roots in northern Stranglethorn

The Current Behaviour is as following: You can see the tablet in the highlighted area but you cannot interact with it.

Expected Behaviour should be as following: being able to interact with the tablet.

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by warscraft360** [comment]
i fixed that should be live soon

**Comment by OMGhixD-OG** [comment]
Closed as it has been resolved by @warscraft360.
