### ISSUE TITLE
[NPC] Portal Trainers

### ISSUE THREAD

**Issue by Zinumwow** [holydeew/WoWHellgarve#18]
-Larimaine Purdue (2485) is missing, she is not in the stormwind portal room
-Milstaff Stormeye (2489) i cannot train portals with him
-Elissa Dumas (4165) she also doesn't teach me the portals

PS: Perhaps there are more portal trainers missing/unable to train. Tested with lvl 21 mage

https://www.wowhead.com/npc=2485/larimaine-purdue
https://www.wowhead.com/npc=2489/milstaff-stormeye
https://www.wowhead.com/npc=4165/elissa-dumas

**Comment by OMGhixD-OG** [comment]
Thank you for reporting this matter. This should now be fixed

Problem was that the NPCs mentioned here along with many others were given PhaseID 6666 which is not even suppose to be a thing.
