### ISSUE TITLE
[BUG] Quest "L'ordre du roi" (Stormwind) , You can't Click on NPC. And Many other Problems with QuestLine StormWind

### ISSUE THREAD

**Issue by synepcice** [holydeew/WoWHellgarve#200]
Quest/Spell/Item/Creature(ID) The ID is: L'ordre du Roi (Stormrwind)

The Current Behaviour is as following: You can't click on NPC to begin the Quest

Expected Behaviour should be as following: You should click on NPC and begin the Quest

Screenshot/Video (IMGUR/YOUTUBE): https://imgur.com/a/WXfJIfu

Additional Information: There is a LOT OF Bugs witch StormWind Quests , You should see all the QuestLine of this Area.

**Comment by holydeew** [comment]
I Fixed the gossip menu for quests hope now its works good. 
if not, open a new ticket and i will investigate whole quest chain.
thank you very much for your report :)
