### ISSUE TITLE
[NPC][Rare][Achievement][Northrend] - Loque'nahak rare npc bug, needed for achievement

### ISSUE THREAD

**Issue by ffighter29** [holydeew/WoWHellgarve#203]
Quest/Spell/Item/Creature(ID) The ID is: 
https://www.wowhead.com/npc=32517/loquenahak
The Current Behaviour is as following: 
NPC is friendly
Expected Behaviour should be as following: 
NPC should be hostile
Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/7666694/114312711-ec78c400-9af3-11eb-9d08-065bb6383441.png)

Additional Information:

**Comment by holydeew** [comment]
Fixed his faction. thank you for your report :)
