### ISSUE TITLE
[BUG]Castle Nathria first 4 mob statues

### ISSUE THREAD

**Issue by Neffy-tech** [holydeew/WoWHellgarve#204]
Quest/Spell/Item/Creature(ID) The ID is: npc=173444/caramain

The Current Behaviour is as following: spawning duplcates on statues in front of first boss

Expected Behaviour should be as following: 1 mob per statues not 2 or 3 or 4 :D

Screenshot/Video (IMGUR/YOUTUBE): -

Additional Information:-

**Comment by holydeew** [comment]
FiXED, thank you
