### ISSUE TITLE
[BUG]first of all i have a bug quest in the exile zone when i reach level 10 with war a quest of the excution spell does not work 

### ISSUE THREAD

**Issue by desporodar** [holydeew/WoWHellgarve#208]
Quest/Spell/Item/Creature(ID) The ID is: ''Hjalmar's final excution'' this quest in the LS zone level 10 war does not work 

The Current Behaviour is as following: npc dont react to the quest properly 

Expected Behaviour should be as following : 

Screenshot/Video (IMGUR/YOUTUBE): 
![WoWScrnShot_041421_054208](https://user-images.githubusercontent.com/82492829/114659799-23192f00-9cec-11eb-9896-b57534bb8b84.jpg)

Additional Information:

**Comment by holydeew** [comment]
Hello, can you please test again, and open a new ticket or send me DM in discord. if it still bug, 
thank you
