### ISSUE TITLE
[BUG][NPC][Pandaria][Jade Forest][Rare] - Mister Ferocius

### ISSUE THREAD

**Issue by ffighter29** [holydeew/WoWHellgarve#213]
Quest/Spell/Item/Creature(ID) The ID is: 
https://www.wowhead.com/npc=50823/mister-ferocious
The Current Behaviour is as following: 
NPC is friendly and cant be attacked
Expected Behaviour should be as following: 
NPC should be hostile 
Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/7666694/115126294-48e55300-9fce-11eb-9290-c3a5db8c9201.png)

Additional Information:
counts towards: https://www.wowhead.com/achievement=7438/could-we-find-more-like-that

**Comment by subsix-wow** [comment]
@holydeew 

UPDATE `kyrianworld`.`creature_template` SET  `faction`='14' WHERE  `entry`=50823;

**Comment by holydeew** [comment]
FIXED, thank you
