### ISSUE TITLE
[BUG][NPC][Rare][Pandaria][Timeless Isle] - Crimsonscale Firestorm can not be reached

### ISSUE THREAD

**Issue by ffighter29** [holydeew/WoWHellgarve#214]
Quest/Spell/Item/Creature(ID) The ID is: 
https://www.wowhead.com/npc=72876/crimsonscale-firestorm
The Current Behaviour is as following: 
NPC can no be reached
Expected Behaviour should be as following: 
either make him move (patrol) or make him lower to the ground
Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/7666694/115136891-0bf77b80-a023-11eb-8f15-d6702095eba1.png)

Additional Information:

**Comment by subsix-wow** [comment]
@holydeew 

UPDATE `kyrianworld`.`creature` SET `spawndist`='3', `MovementType`='1' WHERE  `id`=72876;

**Comment by holydeew** [comment]
FIXED, thank you :)
