### ISSUE TITLE
[BUG] Quest Ogres to the Slaughter

### ISSUE THREAD

**Issue by VanixxWoW** [holydeew/WoWHellgarve#217]
Quest/Spell/Item/Creature(ID) The ID is: 55988

The Current Behaviour is as following: NPC for Finish is under the Map

Expected Behaviour should be as following: Should be standng in front of a big Door

Screenshot/Video (IMGUR/YOUTUBE): https://youtu.be/Sx0EBcTHAfM

Additional Information:

**Comment by holydeew** [comment]
Sorry for the delay, it will be spawned right soon as possible.
