### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Retroliser** [holydeew/WoWHellgarve#218]
Quest/Spell/Item/Creature(ID) The ID is: "Rest and Relaxation"

The Current Behaviour is as following: Quest Giver provides 2 instances of the quest; "Rest and Relaxation".

Expected Behaviour should be as following: Quest Giver should provide only 1 instance of "Rest and Relaxation".

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/83100047/115940104-41bfb880-a498-11eb-97d1-0ed129138c3a.png)

Additional Information:

**Comment by subsix-wow** [comment]
DELETE FROM `kyrianworld`.`creature_queststarter` WHERE  `id`=6774 AND `quest`=2158;
DELETE FROM `kyrianworld`.`creature_questender` WHERE  `id`=295 AND `quest`=2158;

**Comment by holydeew** [comment]
FIXED, thank you :)
