### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Retroliser** [holydeew/WoWHellgarve#219]
Quest/Spell/Item/Creature(ID) The ID is: Roberto Pupellyverbos <Merlot Connoisseur>

The Current Behaviour is as following: Two instances of Roberto exist at the Gallina Winery in Stormwind.

Expected Behaviour should be as following: Only one instance of Roberty should exist.

Screenshot/Video (IMGUR/YOUTUBE): 
![image](https://user-images.githubusercontent.com/83100047/115940717-81879f80-a49a-11eb-819d-b78d7a20d191.png)

Additional Information:

**Comment by subsix-wow** [comment]
@holydeew 

DELETE FROM `kyrianworld`.`creature` WHERE  `id`=277 AND `guid`<>189354;

**Comment by holydeew** [comment]
FIXED, thank you :)
