### ISSUE TITLE
Druid stuck in Pacified mode

### ISSUE THREAD

**Issue by wellytonr** [holydeew/WoWHellgarve#221]
When I am using the travel form and change back to the cat form. 
Sometimes the druid get stuck in pacified mode. 
Tried restarting, logging out and change between the forms and nothing solved the issue.

**Comment by wellytonr** [comment]
![problemdruid](https://user-images.githubusercontent.com/35041905/116875611-9928fb80-abf1-11eb-89bc-d250a0ac2805.png)

**Comment by holydeew** [comment]
Test again please

**Comment by holydeew** [comment]
also if you need some1 to remove that aura open a ticket in discord please.
