### ISSUE TITLE
Atiçando as chamas[BUG]

### ISSUE THREAD

**Issue by Corderim** [holydeew/WoWHellgarve#223]
Quest/Spell/Item/Creature(ID) The ID is: Atiçando as chamas

The Current Behaviour is as following: 

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information: A missão não esta evocando o elemento vivo de ar para ser abatido e finalizar a missao.

**Comment by holydeew** [comment]
presiso de mais detalhes é esta quest?? ->https://www.wowhead.com/quest=29523/fanning-the-flames??
isto é o que está faltando? https://www.wowhead.com/item=72112/fluttering-breeze

**Comment by holydeew** [comment]
I marked that quest as auto-complete to temp.fix it.
you should be able to comtinue now, if it gave you any problem, just take the quest again
