### ISSUE TITLE
Druid spells not working Swiftmend and Rejuvation

### ISSUE THREAD

**Issue by WowLander** [holydeew/WoWHellgarve#33]
i have problem with my resto druid when i go to spec i have three spells are Swiftmend Rejuvation and Regrowith.But i cant drag Swiftmend and Rejuvation from my spec i can drag only Regrowith.PLS HELP ME

**Comment by Lujanamma** [comment]
Can you verify if it is working now?

**Comment by Lujanamma** [comment]
ill close the issue as this is no longer happening. if this occurs again let us know

**Comment by WowLander** [comment]
Thx very much everything is working now:)
