### ISSUE TITLE
Warrior Bugs

### ISSUE THREAD

**Issue by KingHatred** [holydeew/WoWHellgarve#52]
Warrior charge applies 5 seconds 50% movement speed slow and 1 second root upon hitting a target with charge. Tested this on low level, ability description says it should only apply root for 1 second.
War machine: works sometimes, probably based on "honor/experience" or something... think it should work with anything you kill
Sudden death: Execute does NOT consume this proc
Fresh meat: First hit is NOT guaranteed to Enrage, the incresed chance of Enrage from bloodthirst doesnt work
Double time: Possible to use both charges of Charge (hehe) in one global 
Frenzy: Does NOT work at all
Furious Charge: Doesnt increase healing from bloodthirst
Seethe: critical hit with bloodthirst generates 20 rage instead of 12
Cruelty: doesnt proc at all
Meat cleaver: Whirlwind is broken completely... the damage increase for whirlwind works but whirlwind gives you only 1 stack of whirlwind instead of all 4
Dragon roar: Does not reduce damage to secondary targets
Bladestorm: Seems to work fine except its uncapped
Reckless abandon: broken, tirnkets can trigger it, dismounting trigers it, spellreflect triggers it, otherwise everything else works
Siegebreaker: Whirlwind stacks wont apply debuff onto more enemmies but still deals damage, only primary target gets the debuff, debuff works fine
Whirlwind: Only execute bloodthirst and victory rush can benefit from whirlwind stack although they dont consume any, Raging blow consumes 2 stacks of whirlwind and doesnt
       damage secondary targets

Shattering throw: does not deal dmg
Victory rush: Heals per target hit, so if you cleave it with whirlwind it heals per target hit, f.e. 3 targets = 3x30%= 90%maxhp
Dragon roar: Does not reduce damage to secondary targets (my humble opinion: leave it like that, so it can compare to other classes without capped aoe :smile: )
Rampage: doesnt work with whirlwind stacks
Charge: Slows target by 50% for 5 seconds for some reason
Collateral damage: Doesnt work
Cleave: works fine, although think its uncapped, not sure
Deadly calm: abbilities do not consume stacks which means that this gives you free casting for 20 seconds
Dreadnaught: Doesnt work AT ALL (the second stack is not usable and dreadnaught dmg isnt there..., nothings happenin)
Mastery deep wounds DO NOT increase damage done, only apply DoT
Autoattacks generate 28 rage if you respec to fury  and back to arms, otherwise if you log out as arms your aa's generate around 5 rage
Shattering throw: does not deal dmg, not sure if it breaks immunities
colossus smash: sometimes(quite often) it resets its cooldown randomly
warmachine: aa's rage gen is broken, cant say more about this talent
punish: devastate applys the debuff to enemy not only shield slam
devastator: doesnt reset cooldown of shield slam
double time: same issue as with dps spec
Furious charge https://en.wowhead.com/spell=202224/carga-furiosa charge should make the next bloodthirst (https://www.wowhead.com/spell=57792/bloodthirst) heal 250% more
Sudden death https://www.wowhead.com/spell=280721/sudden-death should make attacks have a chance to reset the cooldown of Execute (https://en.wowhead.com/spell=163201/ejecutar) and make it usable on any target, regardless of their health.
Devastator https://en.wowhead.com/spell=236279/devastadora 
auto attacks should deal an additional (22.1% of Attack power) Physical damage and have a 20% chance to reset the remaining cooldown on Shield Slam (https://www.wowhead.com/spell=145045/shield-slam).
Impending Victory for warrior, replaces your victory rush when you first put the point in, but when you logout, it doesnt replace it
die by the sword 118038 you get the effect but it doesnt parry
Warrior Spell: Execute (on Fury spec) not working

**Comment by ffighter29** [comment]
Thumbs up for detailed explanation!
