### ISSUE TITLE
The Scarlet Apocalypse

### ISSUE THREAD

**Issue by GM-shadow** [holydeew/WoWHellgarve#60]
Lich king seems to be out of phase, when in GM mode  i can see but normal players cannot

Quest https://www.wowhead.com/quest=12778/the-scarlet-apocalypse
NPC  https://www.wowhead.com/npc=29110/the-lich-king

tried to spawn but  no luck  for people to hand in Q

**Comment by OMGhixD-OG** [comment]
Should be fixed as of yesterdays update

Thank you for reporting this!
