### ISSUE TITLE
[BUG] Warchief in orgrimmar is inmune, unable to get the Achievement

### ISSUE THREAD

**Issue by Dalkoo** [holydeew/WoWHellgarve#67]
Quest/Spell/Item/Creature(ID) The ID is: 

The Current Behaviour is as following: 

Expected Behaviour should be as following: 

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:

**Comment by Lujanamma** [comment]
Can you kill it now?

**Comment by Lujanamma** [comment]
fixed
