### ISSUE TITLE
[BUG][Spell][Druid][Balance] Starfall deals no damage

### ISSUE THREAD

**Issue by ffighter29** [holydeew/WoWHellgarve#69]
Quest/Spell/Item/Creature(ID) The ID is:  Starfall

The Current Behaviour is as following: Starfall deals no damage

Expected Behaviour should be as following: Starfall should deal damage

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:  https://www.wowhead.com/spell=191034/starfall

**Comment by Lujanamma** [comment]
Hello can you verify if this is working now?

**Comment by Lujanamma** [comment]
fixed

**Comment by ffighter29** [comment]
works! thanks
