### ISSUE TITLE
[BUG] Starfall isn't working

### ISSUE THREAD

**Issue by Hakkun46** [holydeew/WoWHellgarve#78]
Quest/Spell/Item/Creature(ID) The ID is: 191034

The Current Behaviour is as following: Isn't working

Expected Behaviour should be as following: at least starfall should give a damage to an enemy

Screenshot/Video (IMGUR/YOUTUBE): 

Additional Information:
Everytime i use starfall it doesn't do any damage to every mob.(sorry for my bad english)

**Comment by Lujanamma** [comment]
fixed
